server:
  port: 8000

spring:
  application:
    name: ds
  profiles:
    active: dev
  mvc:
    throw-exception-if-no-handler-found: true
    static-path-pattern: /static/**

#配置日志,日志用xml去配置
log:
  dir: ./log


########################################################
#          不同环境         Environment for Localhost  注意：数据配置在这里
########################################################
---
spring:
  jmx:
    enabled: false
  profiles: dev
  servlet:
    multipart:
    max-file-size: 10200MB
    max-request-size: 102400MB
  datasource:
    hikari:
      max-lifetime: 1765000
      maximum-pool-size: 15


arc:
  #主库 MySQL8.0
  datasource:
    db0:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&useAffectedRows=true&useSSL=false&serverTimezone=GMT%2B8
      url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&useAffectedRows=true&useSSL=false&serverTimezone=GMT%2B8
      username: root
      password: admin
    db1:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://127.0.0.1:3306/test5?useUnicode=true&characterEncoding=UTF-8&useAffectedRows=true&useSSL=false&serverTimezone=GMT%2B8
      url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&useAffectedRows=true&useSSL=false&serverTimezone=GMT%2B8
      username: root
      password: admin
